# Settings for the app
app:
  # HTML Title
  title: City of Boston Participatory Budgeting
  # Header name
  name: Participatory Budgeting
  # Meta description that will show up in Google search results
  meta_description: _(Shareabouts is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.)
  # Meta author that will show up in Google search results
  meta_author: OpenPlans.org


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: true
  # The default geocoding engine is MapQuest. You can set an override below.
  # Make sure to provide the appropriate keys for whatever you set.
  geocoding_engine: Mapbox
  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [39.830159, -75.478821, 40.167331, -74.781189]  # top, left, bottom, right

  options:
    center:
      lat: 42.3189
      lng: -71.0689
    zoom: 11.5
    zoomSnap: 0
    minZoom: 10
    maxZoom: 17
    scrollWheelZoom: false
  layers:
    # Raster Tile Layers
    # ==================
    # - url: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
    #   attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'

    # Mapbox GL Layers
    # ================
    - type: mapbox
      style: mapbox://styles/poepublic/clrgpjg9h00bz01mef8atgnpl
      accessToken: pk.eyJ1IjoicG9lcHVibGljIiwiYSI6ImNpaDZnYXNxZDBiajlzd20yd2ZwZXhkb3QifQ.XYIHS6tfEXqoiyximdmLXg
      fallback:
        url: https://api.mapbox.com/styles/v1/poepublic/clrgpjg9h00bz01mef8atgnpl/tiles/256/{z}/{x}/{y}@2x
        attribution: '© <a href="https://www.mapbox.com/about/maps/">Mapbox</a> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> <strong><a href="https://www.mapbox.com/map-feedback/" target="_blank">Improve this map</a></strong>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  arts_culture:
    label: _(Arts & Culture)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "arts_culture" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#fb4d42'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "arts_culture" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#fb4d42'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  community:
    label: _(Community Resources)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "community" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#fa8b41'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "community" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#fa8b41'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  economy_workers:
    label: _(Local Economy & Worker Empowerment)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "economy_workers" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#fac241'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "economy_workers" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#fac241'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  education_youth:
    label: _(Education, Youth & Families)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "education_youth" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#faee41'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "education_youth" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#faee41'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  sustainability:
    label: _(Environment, Sustainability, and Food Access)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "sustainability" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#b6fa41'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "sustainability" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#b6fa41'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  facilities:
    label: _(Facilities, Parks & Recreation  )
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "facilities" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#75fa41'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "facilities" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#75fa41'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  human_services:
    label: _(Human Services / Public Health)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "human_services" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#41eafa'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "human_services" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#41eafa'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  public_safety:
    label: _(Public Safety)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "public_safety" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#4185fa'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "public_safety" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#4185fa'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  streets_sidewalks:
    label: _(Streets & Sidewalks)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "streets_sidewalks" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#4441fa'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "streets_sidewalks" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#4441fa'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  transportation:
    label: _(Transportation )
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "transportation" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#8b41fa'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "transportation" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#8b41fa'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1
  other:
    label: _(Other / Not Sure)
    rules:
      # Draw small circles when zoomed out to see a lot of the ideas...
      - condition: '"{{location_type}}" === "other" && {{map.zoom}} < 13 && {{layer.focused}} === false'
        style:
          color: '#e441fa'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1
      # Draw larger circles when fewer ideas visible...
      - condition: '"{{location_type}}" === "other" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        style:
          color: '#e441fa'
          radius: 6
          weight: 3
          opacity: 0.7
          fillOpacity: 1

  # landmark:
  #   label: _(Landmark)
  #   rules:
  #     - condition: '"{{location_type}}" === "landmark" && {{map.zoom}} < 13 && {{layer.focused}} === false'
  #       # Display landmarks as circles (vectors) when zoomed out

  #       style:
  #         color: '#0d85e9'
  #         radius: 3
  #         weight: 1
  #         opacity: 0.9
  #         fillOpacity: 1

  #     - condition: '"{{location_type}}" === "landmark" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
  #       # Display landmarks as icons when zoomed in

  #       icon:
  #         iconUrl: /static/css/images/markers/dot-0d85e9.png
  #         iconSize: [17, 18]
  #         iconAnchor: [9, 9]

  #     - condition: '"{{location_type}}" === "landmark" && {{layer.focused}} === true'
  #       # Display landmarks as icons when focused/selected

  #       icon:
  #         iconUrl: /static/css/images/markers/marker-0d85e9.png
  #         shadowUrl: /static/css/images/marker-shadow.png
  #         iconSize: [25, 41]
  #         shadowSize: [41, 41]
  #         iconAnchor: [12, 41]

  # park:
  #   label: _(Park)
  #   rules:
  #     - condition: '"{{location_type}}" === "park" && {{layer.focused}}'
  #       # Show parks that are points as icons...

  #       icon:
  #         iconUrl: /static/css/images/markers/marker-4bbd45.png
  #         shadowUrl: /static/css/images/marker-shadow.png
  #         iconSize: [25, 41]
  #         shadowSize: [41, 41]
  #         iconAnchor: [12, 41]

  #       # ...and parks that are polygons as shapes.

  #       style:
  #         color: '#4bbd45'
  #         weight: 3
  #         opacity: 0.9
  #         fillOpacity: 0.7

  #     - condition: '"{{location_type}}" === "park"'
  #       # Show parks that are points as icons...

  #       icon:
  #         iconUrl: /static/css/images/markers/dot-4bbd45.png
  #         iconSize: [17, 18]
  #         iconAnchor: [9, 9]

  #       # ...and parks that are polygons as shapes.

  #       style:
  #         color: '#4bbd45'
  #         weight: 1
  #         opacity: 0.9
  #         fillOpacity: 0.4

  # school:
  #   label: _(School)
  #   rules:
  #     - condition: '"{{location_type}}" === "school" && {{submission_sets.comments.length}} > 0'
  #       # Display schools as circles

  #       style:
  #         color: '#f95016'
  #         radius: 8
  #         weight: 4
  #         opacity: 0.9
  #         fillOpacity: 0.4
  #       focus_style:
  #         color: '#f95016'
  #         radius: 16
  #         weight: 4
  #         opacity: 0.9
  #         fillOpacity: 0.4

  #     - condition: '"{{location_type}}" === "school"'
  #       style:
  #         color: '#f95016'
  #         radius: 8
  #         weight: 1
  #         opacity: 0.9
  #         fillOpacity: 0.4
  #       focus_style:
  #         color: '#f95016'
  #         radius: 16
  #         weight: 1
  #         opacity: 0.9
  #         fillOpacity: 0.4


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported:
    from: '2017-03-07 00:00 -0500'   # Daylight savings begins mid-March
    until: '2099-04-07 00:00 -0400'  # and ends mid-October.
  editors: place-editors
  moderators: place-editors
  response_name: _(idea)
  response_plural_name: _(ideas)
  add_button_label: _(Suggest an Idea)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Ideas)
  show_map_button_label: _(Show the Map)
  action_text: _(submitted)
  title: _(Tell us more...)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location
  city_wide_location_label: _(Multiple locations throughout the city)
  city_wide_location_center:  [-71.05804664749975, 42.36058038175507]  # <- Boston City Hall
  city_wide_location_offset: 50  # Within 50 meters of City Hall
  unset_location_label: _(Drag the map to set the location.)

  items:
    - prompt: _(What do you call your idea?)
      label: _(Idea title)
      type: text
      name: title
    - prompt: _(Please share a short (less than 100 words) description of the project idea?)
      label: _(My idea is to...)
      type: textarea
      name: description

    - prompt: _(Is your idea...)
      label: _(City wide?)
      type: radiogroup
      name: city_wide
      options:
        - label: _(Location-specific)
          value: no
        - label: _(City-wide)
          value: yes
      attrs:
        - key: required
          value: true
    - prompt: _(Approximately where would your idea go?)
      label: _(Approximate location...)
      type: location
      name: address
      placeholder: _(Drag the map to set the location.)

    - prompt: _(Please describe the positive impact of your project idea to the community.)
      label: _(This idea would benefit the community by...)
      type: textarea
      name: benefit
    - prompt: _(Which category does your idea fall into?)
      label: _(Category)
      help_text: _(Choose the category that most closely describes your project.)
      type: radiogroup
      name: location_type
      options:
        - label: _(Arts & Culture)
          value: arts_culture
        - label: _(Community Resources)
          value: community
        - label: _(Local Economy & Worker Empowerment)
          value: economy_workers
        - label: _(Education, Youth & Families)
          value: education_youth
        - label: _(Environment, Sustainability, and Food Access)
          value: sustainability
        - label: _(Facilities, Parks & Recreation  )
          value: facilities
        - label: _(Human Services / Public Health)
          value: human_services
        - label: _(Public Safety)
          value: public_safety
        - label: _(Streets & Sidewalks)
          value: streets_sidewalks
        - label: _(Transportation )
          value: transportation
        - label: _(Other / Not Sure)
          value: other
      attrs:
        - key: required

    # Personal info
    - prompt: _(Your Name)
      label: _(Submitter's Name)
      type: text
      name: submitter_name
      sticky: true
      attrs:
        - key: size
          value: 30
    - prompt: _(Your Neighborhood)
      label: _(Submitter's Neighborhood)
      type: text
      name: submitter_neighborhood
      sticky: true
      attrs:
        - key: size
          value: 30
    - prompt: _(Your Zip Code)
      label: _(Your Zip Code)
      type: text
      name: private-submitter_zipcode
      optional: true
      sticky: true
      attrs:
        - key: size
          value: 10
    - prompt: _(Your Email)
      label: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      sticky: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30

survey:
  submission_type: comments
  adding_supported: false

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:

support:
  submission_type: support
  adding_supported: false
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(Boston PB Home)
    external: true
    url: https://www.boston.gov/departments/participatory-budgeting

  - title: Filter Places
    slug: filter-type
    pages:
      - title: All
        external: true
        url: /filter/all
      - title: _(Landmark)
        url: /filter/landmark
        external: true
      - title: _(Park)
        url: /filter/park
        external: true
      - title: _(School)
        url: /filter/school
        external: true

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email
